### ISSUE TITLE
user_performance() & leaderboard()

### ISSUE THREAD

**Issue by vonGameTheory** [Omni-Analytics-Group/Rnumerai#14]
leaderboard(), which had not seemed to have worked at all since I started using Rnumerai (a few weeks ago) now returns results but the header is mismatched with the data

and user_performance(), which had been working fine up until yesterday, now returns an error

(Those are the only functions I've used besides setting the api keys, so if any others are having trouble I wouldn't have noticed.)

**Comment by yogesh-bansal** [comment]
Thanks for pointing out the issue, The API changed the order in which it returned the stats, And unfortunately, The results were parsed using index.
But now they are being parsed using names and the issue is fixed.

Please install the fresh version from Github `devtools::install_github("Omni-Analytics-Group/Rnumerai")` and reload the R session.
Let us know if you face any other issues in the package.
